- name: install NGINX webserver
  become: True
  apt:
    name: nginx
    cache_valid_time: "{{ cache_update_valid_secs }}"

- name: install NGINX configuration
  become: True
  template:
    src: 05_nginx.j2
    dest: /etc/nginx/nginx.conf

- name: restart nginx
  become: True
  service:
    name: nginx
    state: restarted

